import React from "react";
import Head from "next/head";
import styles from "@/styles/createModify-page.module.css";
import { CreateBackground, ClosePage2, PreviewInvoice } from "@/components/createModify";

export default function PreviewCreateInvoice() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/teapot.png" />
			</Head>
			<main>
				<div className={styles.createBackground}>
					<CreateBackground />
				</div>
				<div className={styles.previewInvoice}>
					<PreviewInvoice />
				</div>
				<div className={`${styles.closePage} ${styles.closePage2}`}>
					<ClosePage2 />
				</div>
			</main>
		</>
	);
}
